### ISSUE TITLE
Unknown column 'aw.award_name' in 'field list'

### ISSUE THREAD

**Issue by patofield** [Spuds/SMF-Member-Awards#40]
Just installed this on my forums 2.0.8 with no install errors. After installing I got this error when I want to visit a topic.

Unknown column 'aw.award_name' in 'field list'
File: /Sources/AwardsManage.php
Line: 46
## 

In Configuration award:

Unknown column 'id_category' in 'where clause'
File: //Sources/AwardsSubs.php
Line: 87
- Fresh install. I hav not installed previous versions of this mod.

**Comment by Spuds** [comment]
Please make sure that the database tables were created correctly during the install.  You should have the following new tables:
awards_members
awards
awards_categories

If you do check in the awards table and let me know if you see an award_name column

It should work fine on 2.08, although I have not really used SMF since 2.03 or there abouts

**Comment by patofield** [comment]
Got it worked now but the awards are not shown in topic view..

Display.template.php:
http://s000.tinyupload.com/index.php?file_id=01118415892826554091

**Comment by GodOfWareFare** [comment]
Hi i get this error from Sources/AwardsSubs.php  SMF 2.0.19
Field 'filename' doesn't have a default value
can you help me fix this please?

**Comment by Spuds** [comment]
Duplicate issue and fixed in https://github.com/Spuds/SMF-Member-Awards/issues/55
